name: Technitium DNS
version: "2026.09.28.03"
slug: technitium_dns
description: Run your own Technitium DNS Server inside Home Assistant
url: https://github.com/drmogie/network-services
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: auto
host_network: true
hassio_api: false
webui: http://[HOST]:[PORT:5380]
watchdog: http://[HOST]:[PORT:5380]/
options:
  admin_username: "admin"
  admin_password: ""
  timezone: "America/Los_Angeles"
schema:
  admin_username: str?
  admin_password: password?
  timezone: str
